language: generic 
sudo: required
services:
- docker
before_install:
  - docker build -t toruk0131/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true toruk0131/react-test npm test

after_install:
  - docker build -t toruk0131/multi-client ./client
  - docker build -t toruk0131/multi-nginx ./nginx
  - docker build -t toruk0131/multi-server ./server
  - docker build -t toruk0131/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push toruk0131/multi-client
  - docker push toruk0131/multi-nginx
  - docker push toruk0131/multi-server
  - docker push toruk0131/multi-worker